name: e_commerce
description: Demonstrates how to use the flutter_face_api plugin.

publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  path_provider: ^2.1.1
  flutter:
    sdk: flutter
  flutter_face_api:
    path: ../
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  image_picker: ^1.1.1
  flutter_tesseract_ocr: ^0.4.24
  nik_validator: ^1.1.2
  image: ^4.1.7
  opencv_4: ^1.0.0
  camera: ^0.10.5+9
  local_auth: ^2.2.0
  flutter_face_core_basic: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/pp-placeholder.webp
    - assets/images/ktp-placeholder.png
    - assets/images/burung.jpeg
    - assets/icon/sold.png
    - assets/images/banner-1.webp
    - assets/images/banner-2.webp
    - assets/produk/1.jpg
    - assets/produk/2.jpg
    - assets/produk/3.jpg
    - assets/produk/4.jpg
    - assets/produk/5.jpg
    - assets/produk/6.jpg
    - assets/produk/7.jpg
    - assets/produk/8.jpg
    - assets/tessdata/
    - assets/tessdata_config.json
  uses-material-design: true
